
###
GET http://localhost:3000/user?page=1&limit=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzIzNzAzMjAwLCJleHAiOjE3MjM3MTA0MDB9.ZDo7Z-xiea37uJ4iJwlXHqg6mSdrDPMJqAcAOV_AjWE

###
POST  http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
GET http://localhost:3000/aa?a=b

###
GET http://localhost:3000/?a=b
