
###
GET http://localhost:3000/user?page=1&limit=1


###
POST  http://localhost:3000/login
Content-Type: application/json

{
  "username": "22",
  "password": "admin"
}

###
GET http://localhost:3000/aa?a=b

###
GET http://localhost:3000/?a=b
