
###
POST  http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzIzNzE1MjI4LCJleHAiOjE3MjM3MjI0Mjh9.KCWoZh7sy1ZyIcMPTvXUvETnkzJSRqTBXKPkwE9d_Bs

{
  "username": "guest",
  "password": "guest",
  "email": "d",
  "mobile": "b",
  "status": 1
}

###
GET http://localhost:3000/user?page=1&limit=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzIzNzE1MjI4LCJleHAiOjE3MjM3MjI0Mjh9.KCWoZh7sy1ZyIcMPTvXUvETnkzJSRqTBXKPkwE9d_Bs

###
POST  http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
GET http://localhost:3000/aa?a=b

###
GET http://localhost:3000/?a=b
